language: scala

jdk:
   - oraclejdk8
scala:
   - 2.12.2

script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt coveralls
